### ISSUE TITLE
Python 3 friendly?

### ISSUE THREAD

**Issue by kseistrup** [google/pyringe#15]
Seeing a `print 'some string'` statement in the code I gather that `pyringe` is python 2 only.  However, it would be nice to see this announced on the frontpage and on PyPI.

Cheers.

**Comment by TehMillhouse** [comment]
The situation is a bit weird here. There's not only one version of python we care about, but three:
- The one under which pyringe is running
- The version of the inferior
- The version of `libpython.so` gdb was built / linked against

All of these are relevant, so there should be information about python2/3 friendliness for all of these.

**Comment by TehMillhouse** [comment]
Added a section to the README about this in 50ea69ff30370c0ca4cc6cd6c0569f553f924363. Due to the non-binary state of this (it depends on gdb build and whether we're talking about inferior or superior), I'd like to keep it out of the package tags.

**Comment by kseistrup** [comment]
That's fine, thanks.
